### ISSUE TITLE
Failed to connect to Mir: Failed to connect to server socket: No such file or directory ?

### ISSUE THREAD

**Issue by Inkimar** [DrSnowbird/eclipse-photon-docker#1]
Getting this Error when running:
```
No protocol specified
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
Eclipse: Cannot open display
```

did I miss something obvious in the README.md ?

**Comment by DrSnowbird** [comment]
This blog explains very well for why and how to solve your issue.
https://askubuntu.com/questions/871092/failed-to-connect-to-mir-failed-to-connect-to-server-socket-no-such-file-or-di

Basically, Eclipse needs X11 display server on your host machine. The error you encountered said that it can't find the host's X11 display server - no X11 server running. Normally, an
   export DISPLAY=:0.0 
before running the ",/run.sh" should solve the problem.

However, one other change is to
   xhost +
to allow any X11 client to connect to your Host.

In all, the "run.sh" script has all the "export DISPLAY=:0.0" setup already -- changed from using actual host's IP address since some other Linux OS might not have support the parsing of getting actual IP address; so, to be universal, I modified to just use default loop IP address to avoid possible issue.

Please try again using the "./run.sh" to see whether that solves your problem now.

**Comment by DrSnowbird** [comment]
Other users have validated the fixes above solve the issue.
If you feel not solving the issue yet, please open again. Thanks.
